Repository cargo-bins/cargo-binstall, pull requests merged in 2022-07, with the labels that each got.

#207 Refactor: Rm global variable `helpers::Client`
  Cargo.lock
  Cargo.toml
  src/drivers/crates_io.rs
  src/fetchers.rs
  src/fetchers/gh_crate_meta.rs
  src/fetchers/quickinstall.rs
  src/helpers.rs
  src/main.rs
Labels: PR: improvement

#209 Refactor: Confirm only once and move all confirmations into `entry`
  src/main.rs
Labels: PR: improvement

#210 Feature: Support specifing versions via `crate_name@req`
  src/errors.rs
  src/helpers.rs
  src/helpers/crate_name.rs
  src/main.rs
Labels: PR: feature work

#216 Feature: Implement batch installation
  Cargo.lock
  Cargo.toml
  ci-scripts/run_tests_unix.sh
  src/helpers.rs
  src/helpers/crate_name.rs
  src/main.rs
  src/metafiles/cvs.rs
  src/target.rs
Labels: PR: feature work

#218 Use `opt-level = "z"` for release
  Cargo.toml
Labels: PR: improvement

#217 Refactor: Extract new mod `binstall`
  src/binstall.rs
  src/binstall/install.rs
  src/binstall/resolve.rs
  src/helpers.rs
  src/helpers/jobserver_client.rs
  src/lib.rs
  src/main.rs
Labels: PR: improvement

#220 Forbid --manifest-path to used with batch installation
  src/errors.rs
  src/main.rs
Labels: PR: improvement

#222 Refactor: Make appending to metafiles easier and fix their err handling
  src/binstall/install.rs
  src/metafiles/cvs.rs
  src/metafiles/v1.rs
  src/metafiles/v2.rs
Labels: PR: improvement

#223 Fix: join err handling, unify it using `BinstallError`
  src/errors.rs
  src/helpers.rs
  src/main.rs
Labels: PR: improvement

#226 Fix race condition when updating metafile
  src/binstall.rs
  src/binstall/install.rs
  src/main.rs
  src/metafiles/v1.rs
  src/metafiles/v2.rs
Labels: PR: bugfix

#225 Fix: Create `temp_dir` in `install_path`
  src/main.rs
Labels: PR: improvement

#227 Fix updating metafiles: Use file lock to fix race condition
  Cargo.lock
  Cargo.toml
  src/helpers.rs
  src/helpers/flock.rs
  src/metafiles/v1.rs
  src/metafiles/v2.rs
Labels: PR: bugfix

#228 Fix updating metafiles: Skip on custom install path
  ci-scripts/run_tests_unix.sh
  src/helpers.rs
  src/main.rs
Labels: PR: bugfix

#224 Releng improvements
  .github/workflows/build-and-integration-tests.yml
  .github/workflows/release-pr.yml
  .github/workflows/release-tag.yml
  Cargo.toml
  build.rs
  manifest.rc
  release.toml
  windows.manifest
Labels: PR: improvement

#230 Speedup ci by using liblzma-dev, libzip and libzstd provided by `apt`
  .github/workflows/build-and-integration-tests.yml
  .github/workflows/unit-tests.yml
  Cargo.lock
  Cargo.toml
  Cross.toml
  ci-scripts/install-deps.sh
Labels: PR: improvement

#231 Try to reenable armv7, aarch64 gnu targets
  .github/workflows/build-and-integration-tests.yml
  Cross.toml
Labels: PR: improvement

#235 Remove support for .crates2.json
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/metafiles.rs
  src/metafiles/v2.rs
Labels: PR: improvement

#233 Replace toml with toml_edit
  Cargo.lock
  Cargo.toml
  src/metafiles/v1.rs
Labels: PR: improvement

#236 Find best download source out of alternatives (format extension)
  Cargo.toml
  src/fetchers.rs
  src/fetchers/gh_crate_meta.rs
  src/fetchers/quickinstall.rs
  src/formats.rs
  src/helpers.rs
  src/lib.rs
Labels: PR: improvement

#245 Print out help when `crate_names` is empty
  src/main.rs
Labels: PR: bugfix

#247 Add more features
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  ci-scripts/compile-settings.jq
Labels: PR: improvement

#249 Optimze updating `CratesToml`
  Cargo.lock
  Cargo.toml
  src/bins.rs
  src/binstall.rs
  src/metafiles/v1.rs
Labels: PR: improvement

#250 Add function and example program detecting WASI runability
  examples/detect-wasi.rs
  src/lib.rs
  src/miniwasi.wasm
  src/miniwasi.wast
  src/wasi.rs
Labels: PR: feature work

#252 Feature: Create metafile format for cargo-binstall
  Cargo.lock
  Cargo.toml
  src/binstall.rs
  src/binstall/install.rs
  src/helpers.rs
  src/helpers/flock.rs
  src/main.rs
  src/metafiles.rs
  src/metafiles/binstall_v1.rs
  src/metafiles/cvs.rs
  src/metafiles/v1.rs
Labels: PR: feature work

#259 Add -V, clean up errors and help text
  src/binstall/resolve.rs
  src/errors.rs
  src/helpers.rs
  src/main.rs
Labels: PR: documentation, PR: feature work, PR: improvement

#257 Split features and build args handling in build
  .github/workflows/build.yml
  ci-scripts/compile-settings.jq
Labels: PR: improvement

#256 Use `build-std` feature for release build to reduce binary size
  .github/workflows/build.yml
  ci-scripts/compile-settings.jq
Labels: PR: improvement
